#!/bin/bash

# Print a message while awaiting completion of a command.
# by Todd Stein

# Command's output is captured in $waitFor_output

# $1 is the command you want to run
# $2 is the message you want displayed while waiting for $1 to complete

# Example:
#	waitFor "sleep 5" "Sleeping for 5 seconds..."


waitFor_SHM_FILE="/dev/shm/wait_output.$$"
waitFor_ANIMATION="███▓▒░ ░▒▓"

waitFor_runChild() {
	$1 &>"$waitFor_SHM_FILE"
	kill -s SIGHUP $$
}

waitFor_jobDone() { # on SIGHUP
	trap - SIGHUP
	waitFor_output=$(<"$waitFor_SHM_FILE")
	printf '\r\033[K' 1>&2 # returns cursor to far left and clears the current row
	break 2
}

waitFor_untilHUP() { # display message until SIGHUP
	trap waitFor_jobDone SIGHUP
	local i

	printf "\033[?25l%s  " "$@" 1>&2 # hide cursor and print message
	while :; do
		for ((i=0; i<${#waitFor_ANIMATION}; i++)); do
			local graphic=${waitFor_ANIMATION:$i:1}
			printf "\b%s" "$graphic" 1>&2
			sleep .1
		done
	done
}

waitFor_cleanup() {
	trap - EXIT
	tput cnorm # show cursor
	ps -o ppid,pid $waitFor_child_pid | awk -v parent=$$ '$1==parent { print $2 }' | xargs -r kill 2>/dev/null
	rm -f "$waitFor_SHM_FILE"
}

waitFor() {
	trap waitFor_cleanup EXIT
	waitFor_runChild "$1" &
	waitFor_child_pid=$!
	waitFor_untilHUP "$2"
	waitFor_cleanup
}
